language: java
jdk:
  - openjdk7
#  temporarily disabled JDKs to speed up execution
#  - oraclejdk7
#  - openjdk6
#  - oraclejdk6
before_script:
  - git submodule update --init
script:
  - mvn -f integration-tests/pom.xml test
